<a href="https://colab.research.google.com/github/hodoosol/Start_DL_With_Pytorch/blob/main/Chap3_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 선형 회귀

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [5]:
# 변수 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [6]:
# 크기 출력
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [7]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [8]:
# 가중치와 편향을 초기화해보자.
W = torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [9]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


zeros를 사용해 가중치와 편향을 0으로 초기화 하고, 

requires_grad=True 를 통해 w와 b가 학습을 통해 값이 변경되는 변수임을 명시한다.

현재 가중치 W와 b는 둘 다 0이므로 직선의 방정식은

y = 0 * x + 0 이 된다. 적절하지 않다.

In [10]:
# 가설 세우기
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


수식적으로 단순히 '오차 = 실제값 - 예측값'으로 정의하면 오차값이 음수가 되는 경우가 생기므로 정확한 오차의 크기를 측정할 수 없다. 

따라서 오차를 그냥 전부 더하는 것이 아니라, 

각 오차들을 제곱해준 뒤에 전부 더하는 평균 제곱 오차(Mean Squared Error, MSE)로 비용함수를 만들어 보자.

기울기 w가 무한대로 커지면 커질 수록 cost의 값 또한 무한대로 커지고, 반대로 w가 무한대로 작아져도 cost의 값은 무한대로 커진다. 

따라서 경사하강법을 사용하여 비용 함수를 미분했을 때의 접선의 기울기가 0이 되는 지점을 찾아야 한다.

In [11]:
# 비용 함수 선언하기
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [12]:
# 경사 하강법 구현하기
## SGD는 경사 하강법의 일종이며 lr은 learning rate를 의미한다.
## 학습 대상인 W와 b가 SGD의 입력이 된다.

optimizer = optim.SGD([W, b], lr = 0.01)

In [13]:
# optimizer.zero_grad()를 실행함으로써 미분을 통해 얻은 기울기를 0응로 초기화 한다.
# 기울기를 초기화해야지만 새로운 가중치 편향에 대한 새로운 기울기를 구할 수 있다.
optimizer.zero_grad()

In [14]:
# 그 다음 cost.backward() 함수를 호출하면 W와 b에 대한 기울기가 계산된다.
# 비용 함수를 미분하여 gradient 계산
cost.backward()

In [15]:
# optimizer.step()을 호출하여 인수로 들어갔던 W와 b에서
# 리턴되는 변수들의 기울기에 학습률을 곱하여 빼줌으로써 업데이트한다.

optimizer.step()

전체 코드 정리


In [103]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr = 0.01)

# 원하는 만큼 경사 하강법 반복
nb_epochs = 2000

for epoch in range(nb_epochs + 1) :
  # H(x) 계산
  hypothesis = x_train * W + b

  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번마다 로그 출력
  if epoch % 100 == 0 :
    print('Epoch {:4d} / {} W : {:.3f}, b{:.3f} Cost : {:.6f}'
    .format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0 / 2000 W : 0.187, b0.080 Cost : 18.666666
Epoch  100 / 2000 W : 1.746, b0.578 Cost : 0.048171
Epoch  200 / 2000 W : 1.800, b0.454 Cost : 0.029767
Epoch  300 / 2000 W : 1.843, b0.357 Cost : 0.018394
Epoch  400 / 2000 W : 1.876, b0.281 Cost : 0.011366
Epoch  500 / 2000 W : 1.903, b0.221 Cost : 0.007024
Epoch  600 / 2000 W : 1.924, b0.174 Cost : 0.004340
Epoch  700 / 2000 W : 1.940, b0.136 Cost : 0.002682
Epoch  800 / 2000 W : 1.953, b0.107 Cost : 0.001657
Epoch  900 / 2000 W : 1.963, b0.084 Cost : 0.001024
Epoch 1000 / 2000 W : 1.971, b0.066 Cost : 0.000633
Epoch 1100 / 2000 W : 1.977, b0.052 Cost : 0.000391
Epoch 1200 / 2000 W : 1.982, b0.041 Cost : 0.000242
Epoch 1300 / 2000 W : 1.986, b0.032 Cost : 0.000149
Epoch 1400 / 2000 W : 1.989, b0.025 Cost : 0.000092
Epoch 1500 / 2000 W : 1.991, b0.020 Cost : 0.000057
Epoch 1600 / 2000 W : 1.993, b0.016 Cost : 0.000035
Epoch 1700 / 2000 W : 1.995, b0.012 Cost : 0.000022
Epoch 1800 / 2000 W : 1.996, b0.010 Cost : 0.000013
Epoch 1900 

optimizer.zero_grad() 가 필요한 이유 ?

파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있기 때문이다.

In [21]:
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20

for epoch in range(nb_epochs + 1) :
  z = 2 * w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


# 2. 자동 미분

임의로 2w^2 + 5라는 식을 세워보고, w에 대해서 미분해보자.


In [22]:
# 값이 2인 임의의 스칼라 텐서 w를 선언, 이 텐서에 대한 기울기를 저장
w = torch.tensor(2.0, requires_grad=True)

In [23]:
# 수식 정의하기
y = w ** 2
z = 2 * y + 5

In [24]:
# 수식 z를 w에 대해서 미분하기. backward()는 해당 수식의 w에 대한 기울기를 계산.
z.backward()

In [25]:
# w.grad를 출력하면 w가 속한 수식을 w로 미분한 값을 확인할 수 있다.
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


In [26]:
a = 2 * (w ** 2) + 5
a.backward()
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 16.0


In [31]:
y = w ** 4
d = 2 * y + 5
d.backward()

In [32]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 80.0


In [100]:
w79 = torch.tensor(2.0, requires_grad=True)
y79 = w79 ** 2
z79 = 2 * y79 + 5

z79.backward()
print('수식을 w로 미분한 값 : {}'.format(w79.grad))

수식을 w로 미분한 값 : 8.0


In [102]:
w80 = torch.tensor(2.0, requires_grad=True)
y80 = w80 ** 2
z80 = 2 * (w80 ** 2) + 5

z80.backward()
print('수식을 w로 미분한 값 : {}'.format(w80.grad))

수식을 w로 미분한 값 : 8.0


# 3. 다중 선형 회귀

다수의 x로부터 y를 예측하는 다중 선형 회귀를 공부해보자.

3개의 퀴즈 점수로부터 최종 점수를 예측하는 모델 만들기.

독립 변수 x의 개수가 3개 이므로

H(x) = w1x1 + w2x2 + w3x3 + b

In [35]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [37]:
torch.manual_seed(1)

In [42]:
# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [43]:
# 가중치 w와 b를 선언. w도 3개 선언해야 한다.
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [45]:
# 가설, 비용 함수, 옵티마이저를 선언한 후에 경사 하강법을 1천회 반복한다.

# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


그러나 x의 개수가 3개가 아닌 1000개라면 ??

x_train1 ... x_train1000 을 전부 선언하고

w1 ... w1000 을 전부 선언해야 한다.

이를 해결하기 위해 행렬 곱셈 연산(벡터의 내적)을 사용한다.

In [46]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [47]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [48]:
# 가중치와 편향 선언
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

행렬의 곱셈이 성립되려면

좌측에 있는 행렬의 열 크기 == 우측에 있는 행렬의 행 크기

x_train은 (5, 3)dlrh w는 (3, 1)이므로 가능해진다.

In [50]:
# 가설 선언하기 _ 행렬곱 matmul 사용
hypothesis = x_train.matmul(W) + b

전체 코드 정리

In [53]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer
optimizer = optim.SGD([W, b], lr = 1e-5)

nb_epochs = 20

for epoch in range(nb_epochs + 1) :
  # H(x) 계산
  # 편향 b는 브로드 캐스팅되어 각 샘플에 더해진다.
  hypothesis = x_train.matmul(W) + b
  
  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7861,  95.8280]) Cost: 3069.590820
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

# 4. nn.Module로 구현하는 선형 회귀

In [55]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [56]:
torch.manual_seed(1)

In [57]:
# y = 2x를 가정한 상태에서 만들어진 데이터 (정답 W = 2, b = 0)
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [59]:
# 선형 회귀 모델 구현 _ 모델 선언 및 초기화.
# 단순 선형 회귀이므로 input_dim = 1, output_dim - 1.
# (1, 1) : 하나의 입력 x에 대해서 하나의 출력 y를 가진다.
model = nn.Linear(1, 1)

In [61]:
# model에는 W, b가 저장되어있다. model.parameters()로 출력 가능
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [62]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [63]:
# 전체 훈련 데이터에 대해 경사 하강법을 2천회 반복
nb_epochs = 2000

for epoch in range(nb_epochs + 1) :

  # H(x) 계산
  prediction = model(x_train)

  # cost 계산, 평균 제곱 오차 함수 사용
  cost = F.mse_loss(prediction, y_train)

  # cost로 H(x) 개선
  # gradient를 0으로 초기화
  optimizer.zero_grad()
  # 비용 함수를 미분하여 gradient 계산
  cost.backward()
  # W, b 업데이트
  optimizer.step()

  if epoch & 100 == 0 :
    # 100번 마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 18.562185
Epoch    1/2000 Cost: 14.714844
Epoch    2/2000 Cost: 11.673522
Epoch    3/2000 Cost: 9.269318
Epoch    8/2000 Cost: 2.996658
Epoch    9/2000 Cost: 2.409524
Epoch   10/2000 Cost: 1.945230
Epoch   11/2000 Cost: 1.578036
Epoch   16/2000 Cost: 0.618160
Epoch   17/2000 Cost: 0.527906
Epoch   18/2000 Cost: 0.456377
Epoch   19/2000 Cost: 0.399650
Epoch   24/2000 Cost: 0.249581
Epoch   25/2000 Cost: 0.235080
Epoch   26/2000 Cost: 0.223437
Epoch   27/2000 Cost: 0.214053
Epoch  128/2000 Cost: 0.111904
Epoch  129/2000 Cost: 0.111367
Epoch  130/2000 Cost: 0.110832
Epoch  131/2000 Cost: 0.110300
Epoch  136/2000 Cost: 0.107677
Epoch  137/2000 Cost: 0.107160
Epoch  138/2000 Cost: 0.106645
Epoch  139/2000 Cost: 0.106133
Epoch  144/2000 Cost: 0.103609
Epoch  145/2000 Cost: 0.103112
Epoch  146/2000 Cost: 0.102617
Epoch  147/2000 Cost: 0.102124
Epoch  152/2000 Cost: 0.099695
Epoch  153/2000 Cost: 0.099217
Epoch  154/2000 Cost: 0.098740
Epoch  155/2000 Cost: 0.098266
Epoch

optimizer, hypothesis 과정을 생략하고 model()에 데이터를 직접 넣었다.

In [64]:
# 테스트해보기

# 임의의 입력 4
new_var = torch.FloatTensor([[4.0]])

# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)

# y = 2x 이므로 y = 8이면 제대로 학습된 것이다.
print(pred_y)

tensor([[7.9926]], grad_fn=<AddmmBackward>)


In [65]:
# 학습 후 W와 b의 값을 출력해보자.
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9957]], requires_grad=True), Parameter containing:
tensor([0.0097], requires_grad=True)]


다중 선형 회귀 구현하기

In [66]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [67]:
torch.manual_seed(1)

In [68]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [69]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

학습률은 1e-5(0.00001)로 한다. 

0.01로 하면 모델의 필요한 크기보다 높기 때문에 기울기가 발산한다.

In [72]:
# 학습률을 0.01로 하면 기울기는 발산
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [71]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: nan
Epoch  200/2000 Cost: nan
Epoch  300/2000 Cost: nan
Epoch  400/2000 Cost: nan
Epoch  500/2000 Cost: nan
Epoch  600/2000 Cost: nan
Epoch  700/2000 Cost: nan
Epoch  800/2000 Cost: nan
Epoch  900/2000 Cost: nan
Epoch 1000/2000 Cost: nan
Epoch 1100/2000 Cost: nan
Epoch 1200/2000 Cost: nan
Epoch 1300/2000 Cost: nan
Epoch 1400/2000 Cost: nan
Epoch 1500/2000 Cost: nan
Epoch 1600/2000 Cost: nan
Epoch 1700/2000 Cost: nan
Epoch 1800/2000 Cost: nan
Epoch 1900/2000 Cost: nan
Epoch 2000/2000 Cost: nan


In [77]:
# 기울기를 1e-5로 하면 ? 성공
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = nn.Linear(3,1)

optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [79]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.4789, 0.8222, 0.7059]], requires_grad=True), Parameter containing:
tensor([0.3070], requires_grad=True)]


In [87]:
nb_epochs = 20000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/20000 Cost: 0.202571
Epoch  100/20000 Cost: 0.202349
Epoch  200/20000 Cost: 0.202126
Epoch  300/20000 Cost: 0.201910
Epoch  400/20000 Cost: 0.201690
Epoch  500/20000 Cost: 0.201473
Epoch  600/20000 Cost: 0.201258
Epoch  700/20000 Cost: 0.201052
Epoch  800/20000 Cost: 0.200841
Epoch  900/20000 Cost: 0.200626
Epoch 1000/20000 Cost: 0.200415
Epoch 1100/20000 Cost: 0.200199
Epoch 1200/20000 Cost: 0.200002
Epoch 1300/20000 Cost: 0.199787
Epoch 1400/20000 Cost: 0.199582
Epoch 1500/20000 Cost: 0.199377
Epoch 1600/20000 Cost: 0.199172
Epoch 1700/20000 Cost: 0.198972
Epoch 1800/20000 Cost: 0.198766
Epoch 1900/20000 Cost: 0.198563
Epoch 2000/20000 Cost: 0.198364
Epoch 2100/20000 Cost: 0.198168
Epoch 2200/20000 Cost: 0.197961
Epoch 2300/20000 Cost: 0.197767
Epoch 2400/20000 Cost: 0.197571
Epoch 2500/20000 Cost: 0.197377
Epoch 2600/20000 Cost: 0.197182
Epoch 2700/20000 Cost: 0.196993
Epoch 2800/20000 Cost: 0.196793
Epoch 2900/20000 Cost: 0.196603
Epoch 3000/20000 Cost: 0.196412
Epoch 31

In [88]:
# 모델 테스트

# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.4299]], grad_fn=<AddmmBackward>)


In [89]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9719, 0.4846, 0.5514]], requires_grad=True), Parameter containing:
tensor([0.3523], requires_grad=True)]


# 5. 클래스로 파이토치 모델 구현하기

In [91]:
# 단순 선형 회귀 모델은 model = nn.Linear(1, 1)로 구현했었다.
# 동일 모델을 클래스로 구현해보자.

# torch.nn.Module을 상속받는 파이썬 클래스
class LinearRegressionModel(nn.Module) :
  def __init__(self) :
    super().__init__()
    # 단순 선형 회귀이므로 input_dim = 1, output_dim = 1
    self.linear = nn.Linear(1, 1)

  def forward(self, x) :
    return self.linear(x)

In [92]:
model = LinearRegressionModel()

In [95]:
# 다중 선형 회귀 모델은 model == nn.Linear(3, 1)로 구현했었다.
# 동일 모델을 클래스로 구현해보자.

class MultivariateLinearRegressionModel(nn.Module) :
  def __init__(self) :
    super().__init__()
    self.linear = nn.Linear(3, 1)

  def forward(self, x) :
    return self.linear(x)

In [96]:
model = MultivariateLinearRegressionModel()

# 6. 미니 배치와 데이터 로드

데이터가 굉장히 많을 때, 예를 들어 수십만개 이상이라면 전체 데이터에 대해서

경사 하강법을 수행하는 것은 매우 느릴 뿐만 아니라 많은 계산량이 필요하다. 

어쩌면 메모리의 한계로 불가능할 수도.

이 문제를 해결하기 위해 전체 데이터를 더 작은 단위로 나누어서 학습하는 미니 배치를 사용할 수 있다.

In [104]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [105]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [106]:
# 데이터 입력
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [107]:
# 위의 데이터를 TensorDataset의 입력으로 사용하기 위해 dataset에 저장하자.
dataset = TensorDataset(x_train, y_train)

이제 파이토치의 데이터 세트를 만들었기 때문에 데이터 로더를 사용할 수 있다.

데이터 로더는 기본적으로 데이터셋, 미니 배치의 크기 - > 2개의 인자를 입력받는다.

In [108]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle=True)

In [109]:
# 모델과 옵티마이저를 설계한다.
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [111]:
# 훈련하기 !
nb_epochs = 20

for epoch in range(nb_epochs + 1) :
  for batch_idx, samples in enumerate(dataloader) :
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 0.480877
Epoch    0/20 Batch 2/3 Cost: 2.749199
Epoch    0/20 Batch 3/3 Cost: 1.903234
Epoch    1/20 Batch 1/3 Cost: 1.941651
Epoch    1/20 Batch 2/3 Cost: 1.142585
Epoch    1/20 Batch 3/3 Cost: 3.566102
Epoch    2/20 Batch 1/3 Cost: 3.169156
Epoch    2/20 Batch 2/3 Cost: 2.139808
Epoch    2/20 Batch 3/3 Cost: 1.125601
Epoch    3/20 Batch 1/3 Cost: 0.712265
Epoch    3/20 Batch 2/3 Cost: 2.042973
Epoch    3/20 Batch 3/3 Cost: 2.996371
Epoch    4/20 Batch 1/3 Cost: 1.390489
Epoch    4/20 Batch 2/3 Cost: 2.063843
Epoch    4/20 Batch 3/3 Cost: 1.879563
Epoch    5/20 Batch 1/3 Cost: 1.542500
Epoch    5/20 Batch 2/3 Cost: 2.538434
Epoch    5/20 Batch 3/3 Cost: 0.639810
Epoch    6/20 Batch 1/3 Cost: 2.550020
Epoch    6/20 Batch 2/3 Cost: 0.667031
Epoch    6/20 Batch 3/3 Cost: 2.796340
Epoch    7/20 Batch 1/3 Cost: 2.543345
Epoch    7/20 Batch 2/3 Cost: 1.021681
Epoch    7/20 Batch 3/3 Cost: 0.479373
Epoch    8/20 Batch 1/3 Cost: 1.997885
Epoch    8/20 Batch 2/3 C

In [112]:
# 모델 테스트

# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.0837]], grad_fn=<AddmmBackward>)


# 7. 커스텀 데이터셋

커스텀 데이터셋을 만들 때, 가장 기본적인 뼈대는

In [115]:
# class CustomDataset(torch.utils.data.Dataset) :
#   def __init__(self) :
#     데이터셋의 전처리를 해준다.
  
#   def __len__(self) :
#     데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분.

#   def __getitem__(self, idx) :
#     데이터셋에서 특정 1개의 샘플을 가져오는 함수이다.

커스텀 데이터셋으로 선형 회귀 구현하기

In [116]:
import torch
import torch.nn.functional as F

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [117]:
# 데이터셋 상속
class CustomDataset(Dataset) :
  def __init__(self) :
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self) :
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx) :
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y
  

In [118]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [120]:
model = torch.nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [121]:
# 학습 시작

nb_epochs = 20

for epoch in range(nb_epochs + 1) :
  x_train, y_train = samples

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 3/3 Cost: 4097.970703
Epoch    1/20 Batch 3/3 Cost: 735.258301
Epoch    2/20 Batch 3/3 Cost: 131.919968
Epoch    3/20 Batch 3/3 Cost: 23.669168
Epoch    4/20 Batch 3/3 Cost: 4.246734
Epoch    5/20 Batch 3/3 Cost: 0.761918
Epoch    6/20 Batch 3/3 Cost: 0.136716
Epoch    7/20 Batch 3/3 Cost: 0.024524
Epoch    8/20 Batch 3/3 Cost: 0.004400
Epoch    9/20 Batch 3/3 Cost: 0.000789
Epoch   10/20 Batch 3/3 Cost: 0.000141
Epoch   11/20 Batch 3/3 Cost: 0.000026
Epoch   12/20 Batch 3/3 Cost: 0.000004
Epoch   13/20 Batch 3/3 Cost: 0.000001
Epoch   14/20 Batch 3/3 Cost: 0.000000
Epoch   15/20 Batch 3/3 Cost: 0.000000
Epoch   16/20 Batch 3/3 Cost: 0.000000
Epoch   17/20 Batch 3/3 Cost: 0.000000
Epoch   18/20 Batch 3/3 Cost: 0.000000
Epoch   19/20 Batch 3/3 Cost: 0.000000
Epoch   20/20 Batch 3/3 Cost: 0.000000


In [122]:
# 모델 테스트

# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.7448]], grad_fn=<AddmmBackward>)
